project:
  type: website
  output-dir: docs

website:
  title: "Sports Data Examples"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - auto: "*.qmd"
  repo-url: https://github.com/utdata/sportsdataverse-examples
  repo-actions: [source, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

df-print: paged


